# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "enum_expr"
authors = ["Thomas Makiela <thomak.dev@gmail.com>"]
version = "0.1.0"
edition = "2018"